spring:
  profiles:
    active: dev
  datasource:
     driver-class-name: com.mysql.jdbc.Driver
     url: jdbc:mysql://127.0.0.1:3306/springboot
     username: root
     password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    cache: true
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
  groovy:
    template:
      cache: false
  redis:
  ##数据库索引（默认是0）
    database: 1
    host: 192.168.1.105
    port: 6379
    ##密码默认是空
    password:
    jedis:
      pool:
      ##最大连接数（使用负值表示没有限制）
        max-active: 1000
        ##最大阻塞时间（使用负值表示没有限制）
        max-wait: -1
        ##最大空闲链接
        max-idle: 10
        ##最小空闲连接数
        min-idle: 2
        ##超时时间
    timeout: 5000



##
restart:
  include:
    mapper: /mapper-[\\w-\\.]+jar
    pagehelper: /pagehelper-[\\w-\\.]+jar

##mybatis
mybatis:
  type-aliases-package: com.sprigboot.mybatis.pojo
  mapper-locations: classpath:mapper/*.xml
##mapper
##pagehelper
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql





