spring:
  profiles:
    active: dev
  datasource:
     driver-class-name: com.mysql.jdbc.Driver
     url: jdbc:mysql://127.0.0.1:3306/springboot
     username: root
     password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    cache: true
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
  groovy:
    template:
      cache: false

##
restart:
  include:
    mapper: /mapper-[\\w-\\.]+jar
    pagehelper: /pagehelper-[\\w-\\.]+jar

##mybatis
mybatis:
  type-aliases-package: com.springboot.newGirl.pojo
  mapper-locations: classpath:mapper/*.xml
##mapper
mapper:
  mappers: com.springboot.newGirl.mapper
  not-empty: false
  identity: MYSQL
##pagehelper
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql



